name: Deploy on EC2

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: build repo
        run: |
          sudo npm install --force
          sudo npm run build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/meinPrivateKey
          chmod 600 ~/.ssh/meinPrivateKey
          ssh-keyscan -H ${{secrets.EC2_IP}} >> ~/.ssh/known_hosts

      - name: SSH Connection to EC2 instance
        run: |
          ssh -i ~/.ssh/meinPrivateKey ec2-user@${{secrets.EC2_IP}} << 'ENDSSH'
              sudo yum update -y
              sudo yum upgrade -y
              sudo yum install -y nodejs
              sudo npm install -g serve
          ENDSSH
      - name: Print SCP Command
        run: echo "scp -i ~/.ssh/meinPrivateKey -r build ec2-user@${{secrets.EC2_IP}}:/home/ec2-user/build"
     
      - name: Copy build to EC2
        run: scp -i ~/.ssh/meinPrivateKey -r build ec2-user@${{secrets.EC2_IP}}:/home/ec2-user/build

      - name: Start Calculator on EC2 instance
        run: |
            ssh -i ~/.ssh/meinPrivateKey ec2-user@${{secrets.EC2_IP}} << 'ENDSSH'
                nohup sudo serve -l 80 -s ~/build > /dev/null 2>&1 &
            ENDSSH

      